<%@ Page Title="" Language="C#" MasterPageFile="~/ArtStreet.Master" AutoEventWireup="true" CodeBehind="ArtCulture.aspx.cs" Inherits="ArtStreet.Home.Art_Culture" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div style="align-content: center; vertical-align: top;">
        <div style="border: solid 1px black; padding: 10px;">
            Showing genre introduction:
            <br />
            <asp:DropDownList ID="inp_ddl_ArtCulture" runat="server" AutoPostBack="True" OnSelectedIndexChanged="inp_ddl_ArtCulture_SelectedIndexChanged" Width="100%">
                <asp:ListItem Value=" "></asp:ListItem>
                <asp:ListItem Value="Indian"></asp:ListItem>
                <asp:ListItem Value="Chinese"></asp:ListItem>
                <asp:ListItem Value="Malay"></asp:ListItem>
            </asp:DropDownList>
        </div>
        <div style="overflow-y: scroll; height: 500px; padding: 5px;">
            <asp:MultiView ID="mv_ArtCulture" runat="server">
                <asp:View ID="vw_Indian" runat="server">
                    <h1 id="firstHeading" class="firstHeading mw-first-heading" style="color: rgb(0, 0, 0); margin: 0px 0px 0.25em; padding: 0px; overflow: visible; border-bottom: 1px solid rgb(162, 169, 177); font-size: 1.8em; font-weight: normal; font-family: &quot;Linux Libertine&quot;, Georgia, Times, serif; line-height: 1.3; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Indian art</h1>
                    <div id="bodyContent" class="vector-body" style="font-size: calc(0.875em); line-height: 1.6; position: relative; z-index: 0; color: rgb(32, 33, 34); font-family: sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
                        <div id="siteSub" class="noprint" style="display: block; font-size: 12.88px;">
                            From Wikipedia, the free encyclopedia</div>
                    </div>
                    <p style="margin: 0.5em 0px; color: rgb(32, 33, 34); font-family: sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
                        <b>Indian art</b><span>&nbsp;</span>consists of a variety of art forms, including<span>&nbsp;</span><a href="https://en.wikipedia.org/wiki/Indian_painting" style="text-decoration: none; color: rgb(6, 69, 173); background: none;" title="Indian painting">painting</a>,<span>&nbsp;</span><a href="https://en.wikipedia.org/wiki/Sculpture_in_the_Indian_subcontinent" style="text-decoration: none; color: rgb(6, 69, 173); background: none;" title="Sculpture in the Indian subcontinent">sculpture</a>,<span>&nbsp;</span><a class="mw-redirect" href="https://en.wikipedia.org/wiki/Indian_pottery" style="text-decoration: none; color: rgb(6, 69, 173); background: none;" title="Indian pottery">pottery</a>, and<span>&nbsp;</span><a href="https://en.wikipedia.org/wiki/Textile_arts" style="text-decoration: none; color: rgb(6, 69, 173); background: none;" title="Textile arts">textile arts</a><span>&nbsp;</span>such as<span>&nbsp;</span><a href="https://en.wikipedia.org/wiki/Silk_in_the_Indian_subcontinent#Origin" style="text-decoration: none; color: rgb(6, 69, 173); background: none;" title="Silk in the Indian subcontinent">woven 
                        silk</a>. Geographically, it spans the entire<span>&nbsp;</span><a href="https://en.wikipedia.org/wiki/Indian_subcontinent" style="text-decoration: none; color: rgb(6, 69, 173); background: none;" title="Indian subcontinent">Indian subcontinent</a>, including what is now<span>&nbsp;</span><a href="https://en.wikipedia.org/wiki/India" style="text-decoration: none; color: rgb(6, 69, 173); background: none;" title="India">India</a>,<span>&nbsp;</span><a href="https://en.wikipedia.org/wiki/Pakistan" style="text-decoration: none; color: rgb(6, 69, 173); background: none;" title="Pakistan">Pakistan</a>,<span>&nbsp;</span><a href="https://en.wikipedia.org/wiki/Bangladesh" style="text-decoration: underline; color: rgb(6, 69, 173); background: none;" title="">Bangladesh</a>,<span>&nbsp;</span><a href="https://en.wikipedia.org/wiki/Sri_Lanka" style="text-decoration: none; color: rgb(6, 69, 173); background: none;" title="Sri Lanka">Sri Lanka</a>,<span>&nbsp;</span><a href="https://en.wikipedia.org/wiki/Nepal" style="text-decoration: none; color: rgb(6, 69, 173); background: none;" title="Nepal">Nepal</a>, 
                        and at times eastern<span>&nbsp;</span><a href="https://en.wikipedia.org/wiki/Afghanistan" style="text-decoration: none; color: rgb(6, 69, 173); background: none;" title="Afghanistan">Afghanistan</a>. A strong sense of design is characteristic of Indian art and can be observed in its modern and traditional forms.</p>
                    <p style="margin: 0.5em 0px; color: rgb(32, 33, 34); font-family: sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
                        <asp:Image ID="Image1" runat="server" ImageUrl="https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Mural_painting%2C_monastery_Hemis%2C_Ladakh%2C_India.jpg/330px-Mural_painting%2C_monastery_Hemis%2C_Ladakh%2C_India.jpg" Width="20%" />
                    </p>
                    <p style="margin: 0.5em 0px; color: rgb(32, 33, 34); font-family: sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
                        The origin of Indian art can be traced to<span>&nbsp;</span><a class="mw-redirect" href="https://en.wikipedia.org/wiki/Prehistoric_India" style="text-decoration: none; color: rgb(6, 69, 173); background: none;" title="Prehistoric India">prehistoric</a><span>&nbsp;</span>settlements in the 3rd millennium BC. On its way to modern times, Indian art has had cultural influences, as well as religious influences such as<span>&nbsp;</span><a href="https://en.wikipedia.org/wiki/Hindu_art" style="text-decoration: none; color: rgb(6, 69, 173); background: none;" title="Hindu art">Hinduism</a>,<span>&nbsp;</span><a href="https://en.wikipedia.org/wiki/Buddhist_art" style="text-decoration: none; color: rgb(6, 69, 173); background: none;" title="Buddhist art">Buddhism</a>,<span>&nbsp;</span><a href="https://en.wikipedia.org/wiki/Jain_art" style="text-decoration: none; color: rgb(6, 69, 173); background: none;" title="Jain art">Jainism</a>,<span>&nbsp;</span><a href="https://en.wikipedia.org/wiki/Sikh_art_and_culture" style="text-decoration: none; color: rgb(6, 69, 173); background: none;" title="Sikh art and culture">Sikhism</a><span>&nbsp;</span>and<span>&nbsp;</span><a href="https://en.wikipedia.org/wiki/Islam_in_India#Indo-Islamic_art_and_architecture" style="text-decoration: none; color: rgb(6, 69, 173); background: none;" title="Islam in India">Islam</a>. 
                        In spite of this complex mixture of religious traditions, generally, the prevailing artistic style at any time and place has been shared by the major religious groups.</p>
                    <p style="margin: 0.5em 0px; color: rgb(32, 33, 34); font-family: sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
                        <asp:Image ID="Image2" runat="server" ImageUrl="https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Buddha_in_Sarnath_Museum_%28Dhammajak_Mutra%29.jpg/800px-Buddha_in_Sarnath_Museum_%28Dhammajak_Mutra%29.jpg" Width="20%" />
                    </p>
                    <p style="margin: 0.5em 0px; color: rgb(32, 33, 34); font-family: sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
                        In historic art, sculpture in stone and metal, mainly religious, has survived the Indian climate better than other media and provides most of the best remains. Many of the most important ancient finds that are not in carved stone come from the surrounding, drier regions rather than India itself.<span>&nbsp;</span><a class="mw-redirect" href="https://en.wikipedia.org/wiki/Indian_funeral" style="text-decoration: none; color: rgb(6, 69, 173); background: none;" title="Indian funeral">Indian funeral</a><span>&nbsp;</span>and philosophic traditions exclude<span>&nbsp;</span><a href="https://en.wikipedia.org/wiki/Grave_goods" style="text-decoration: none; color: rgb(6, 69, 173); background: none;" title="Grave goods">grave goods</a>, which is the main source of ancient art in other cultures.</p>
                    <p style="margin: 0.5em 0px; color: rgb(32, 33, 34); font-family: sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
                        <asp:Image ID="Image3" runat="server" ImageUrl="https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/India-5749_-_Visvanatha_Temple_-_Flickr_-_archer10_%28Dennis%29.jpg/1280px-India-5749_-_Visvanatha_Temple_-_Flickr_-_archer10_%28Dennis%29.jpg" Width="20%" />
                    </p>
                    <p style="margin: 0.5em 0px; color: rgb(32, 33, 34); font-family: sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
                        Indian artist styles historically followed<span>&nbsp;</span><a class="mw-redirect" href="https://en.wikipedia.org/wiki/Indian_religion" style="text-decoration: none; color: rgb(6, 69, 173); background: none;" title="Indian religion">Indian religions</a><span>&nbsp;</span>out of the subcontinent, having an especially large influence in<span>&nbsp;</span><a href="https://en.wikipedia.org/wiki/Tibet" style="text-decoration: none; color: rgb(6, 69, 173); background: none;" title="Tibet">Tibet</a>,<span>&nbsp;</span><a class="mw-redirect" href="https://en.wikipedia.org/wiki/South_East_Asia" style="text-decoration: none; color: rgb(6, 69, 173); background: none;" title="South East Asia">South East Asia</a><span>&nbsp;</span>and<span>&nbsp;</span><a href="https://en.wikipedia.org/wiki/China" style="text-decoration: none; color: rgb(6, 69, 173); background: none;" title="China">China</a>. Indian art has itself received influences at times, especially from<span>&nbsp;</span><a href="https://en.wikipedia.org/wiki/Central_Asia" style="text-decoration: none; color: rgb(6, 69, 173); background: none;" title="Central Asia">Central 
                        Asia</a><span>&nbsp;</span>and<span>&nbsp;</span><a href="https://en.wikipedia.org/wiki/Iran" style="text-decoration: none; color: rgb(6, 69, 173); background: none;" title="Iran">Iran</a>, and Europe.</p>
                </asp:View>
                <asp:View ID="vw_Chinese" runat="server">
                    <h1 id="firstHeading0" class="firstHeading mw-first-heading" style="color: rgb(0, 0, 0); margin: 0px 0px 0.25em; padding: 0px; overflow: visible; border-bottom: 1px solid rgb(162, 169, 177); font-size: 1.8em; font-weight: normal; font-family: &quot;Linux Libertine&quot;, Georgia, Times, serif; line-height: 1.3; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Chinese art</h1>
                    <div id="bodyContent0" class="vector-body" style="font-size: calc(0.875em); line-height: 1.6; position: relative; z-index: 0; color: rgb(32, 33, 34); font-family: sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
                        <div id="siteSub0" class="noprint" style="display: block; font-size: 12.88px;">
                            From Wikipedia, the free encyclopedia</div>
                    </div>
                    <p style="margin: 0.5em 0px; color: rgb(32, 33, 34); font-family: sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
                        <b>Chinese art</b><span>&nbsp;</span>is<span>&nbsp;</span><a class="mw-redirect" href="https://en.wikipedia.org/wiki/Visual_art" style="text-decoration: none; color: rgb(6, 69, 173); background: none;" title="Visual art">visual art</a><span>&nbsp;</span>that, whether ancient or modern, originated in or is practiced in China or by Chinese artists. The Chinese art in the<span>&nbsp;</span><a class="mw-redirect" href="https://en.wikipedia.org/wiki/Republic_of_China" style="text-decoration: none; color: rgb(6, 69, 173); background: none;" title="Republic of China">Republic of China</a><span>&nbsp;</span>(Taiwan) and that of<span>&nbsp;</span><a href="https://en.wikipedia.org/wiki/Overseas_Chinese" style="text-decoration: none; color: rgb(6, 69, 173); background: none;" title="Overseas Chinese">overseas Chinese</a><span>&nbsp;</span>can also be considered part of Chinese art where it is based in or draws on Chinese heritage and<span>&nbsp;</span><a href="https://en.wikipedia.org/wiki/Chinese_culture" style="text-decoration: none; color: rgb(6, 69, 173); background: none;" title="Chinese culture">Chinese 
                        culture</a>. Early &quot;<a href="https://en.wikipedia.org/wiki/Stone_Age" style="text-decoration: none; color: rgb(6, 69, 173); background: none;" title="Stone Age">Stone Age</a><span>&nbsp;</span>art&quot; dates back to 10,000 BC, mostly consisting of simple<span>&nbsp;</span><a href="https://en.wikipedia.org/wiki/Pottery" style="text-decoration: none; color: rgb(6, 69, 173); background: none;" title="Pottery">pottery</a><span>&nbsp;</span>and sculptures. After this early period Chinese art, like Chinese history, is typically classified by the succession of ruling<span>&nbsp;</span><a href="https://en.wikipedia.org/wiki/Dynasty" style="text-decoration: none; color: rgb(6, 69, 173); background: none;" title="Dynasty">dynasties</a><span>&nbsp;</span>of<span>&nbsp;</span><a class="mw-redirect" href="https://en.wikipedia.org/wiki/Chinese_emperors" style="text-decoration: none; color: rgb(6, 69, 173); background: none;" title="Chinese emperors">Chinese emperors</a>, most of which lasted several hundred years.</p>
                    <p style="margin: 0.5em 0px; color: rgb(32, 33, 34); font-family: sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
                        <asp:Image ID="Image4" runat="server" ImageUrl="https://upload.wikimedia.org/wikipedia/commons/e/e0/Imaginary_tour_through_Xiao-xiang.jpg" Width="30%" />
                    </p>
                    <p style="margin: 0.5em 0px; color: rgb(32, 33, 34); font-family: sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
                        Chinese art has arguably the oldest continuous tradition in the world, and is marked by an unusual degree of continuity within, and consciousness of, that tradition, lacking an equivalent to the Western collapse and gradual recovery of classical styles. The media that have usually been classified in the West since the<span>&nbsp;</span><a href="https://en.wikipedia.org/wiki/Renaissance" style="text-decoration: none; color: rgb(6, 69, 173); background: none;" title="Renaissance">Renaissance</a><span>&nbsp;</span>as the<span>&nbsp;</span><a href="https://en.wikipedia.org/wiki/Decorative_arts" style="text-decoration: none; color: rgb(6, 69, 173); background: none;" title="Decorative arts">decorative arts</a><span>&nbsp;</span>are extremely important in Chinese art, and much of the finest work was produced in large workshops or factories by essentially unknown artists, especially in<span>&nbsp;</span><a href="https://en.wikipedia.org/wiki/Chinese_ceramics" style="text-decoration: none; color: rgb(6, 69, 173); background: none;" title="Chinese ceramics">Chinese 
                        ceramics</a>.</p>
                    <p style="margin: 0.5em 0px; color: rgb(32, 33, 34); font-family: sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
                        <asp:Image ID="Image5" runat="server" ImageUrl="https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Qian_Xuan_-_Early_Autumn.jpg/1920px-Qian_Xuan_-_Early_Autumn.jpg" Width="30%" />
                    </p>
                    <p style="margin: 0.5em 0px; color: rgb(32, 33, 34); font-family: sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
                        Much of the best work in ceramics, textiles,<span>&nbsp;</span><a href="https://en.wikipedia.org/wiki/Carved_lacquer" style="text-decoration: none; color: rgb(6, 69, 173); background: none;" title="Carved lacquer">carved lacquer</a>, and other techniques was produced over a long period by the various Imperial factories or workshops, which as well as being used by the court was distributed internally and abroad on a huge scale to demonstrate the wealth and power of the Emperors. In contrast, the tradition of<span>&nbsp;</span><a href="https://en.wikipedia.org/wiki/Ink_wash_painting" style="text-decoration: none; color: rgb(6, 69, 173); background: none;" title="Ink wash painting">ink wash painting</a>, practiced mainly by<span>&nbsp;</span><a href="https://en.wikipedia.org/wiki/Scholar-official" style="text-decoration: none; color: rgb(6, 69, 173); background: none;" title="Scholar-official">scholar-officials</a><span>&nbsp;</span>and court painters especially of<span>&nbsp;</span><a href="https://en.wikipedia.org/wiki/Landscape_painting" style="text-decoration: none; color: rgb(6, 69, 173); background: none;" title="Landscape painting">landscapes</a>, 
                        flowers, and birds, developed<span>&nbsp;</span><a class="mw-redirect" href="https://en.wikipedia.org/wiki/Aesthetic" style="text-decoration: none; color: rgb(6, 69, 173); background: none;" title="Aesthetic">aesthetic</a><span>&nbsp;</span>values depending on the individual imagination of and objective observation by the artist that are similar to those of the West, but long pre-dated their development there. After contacts with Western art became increasingly important from the 19th century onwards, in recent decades China has participated with increasing success in worldwide<span>&nbsp;</span><a href="https://en.wikipedia.org/wiki/Contemporary_art" style="text-decoration: none; color: rgb(6, 69, 173); background: none;" title="Contemporary art">contemporary art</a>.</p>
                </asp:View>
                <asp:View ID="vw_Malay" runat="server">
                    <h1 id="firstHeading1" class="firstHeading mw-first-heading" style="color: rgb(0, 0, 0); margin: 0px 0px 0.25em; padding: 0px; overflow: visible; border-bottom: 1px solid rgb(162, 169, 177); font-size: 1.8em; font-weight: normal; font-family: &quot;Linux Libertine&quot;, Georgia, Times, serif; line-height: 1.3; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Malaysian art</h1>
                    <div id="bodyContent1" class="vector-body" style="font-size: calc(0.875em); line-height: 1.6; position: relative; z-index: 0; color: rgb(32, 33, 34); font-family: sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
                        <div id="siteSub1" class="noprint" style="display: block; font-size: 12.88px;">
                            From Wikipedia, the free encyclopedia</div>
                    </div>
                    <p style="margin: 0.5em 0px; color: rgb(32, 33, 34); font-family: sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
                        Traditional Malaysian art is primarily composed of<span>&nbsp;</span><a href="https://en.wikipedia.org/wiki/Malays_(ethnic_group)" style="text-decoration: none; color: rgb(6, 69, 173); background: none;" title="Malays (ethnic group)">Malay art</a><span>&nbsp;</span>and<span>&nbsp;</span><a href="https://en.wikipedia.org/wiki/Dayak_people" style="text-decoration: none; color: rgb(6, 69, 173); background: none;" title="Dayak people">Bornean art</a>, is very similar with the other styles from Southeast Asia, such as<span>&nbsp;</span><a href="https://en.wikipedia.org/wiki/Bruneian_art" style="text-decoration: none; color: rgb(6, 69, 173); background: none;" title="Bruneian art">Bruneian</a>,<span>&nbsp;</span><a href="https://en.wikipedia.org/wiki/Indonesian_art" style="text-decoration: none; color: rgb(6, 69, 173); background: none;" title="Indonesian art">Indonesian</a><span>&nbsp;</span>and<span>&nbsp;</span><a href="https://en.wikipedia.org/wiki/Culture_of_Singapore" style="text-decoration: none; color: rgb(6, 69, 173); background: none;" title="Culture of Singapore">Singaporean</a>. 
                        Art has a long tradition in Malaysia, with Malay art that dating back to the Malay sultanates, has always been influenced by<span>&nbsp;</span><a href="https://en.wikipedia.org/wiki/Chinese_art" style="text-decoration: none; color: rgb(6, 69, 173); background: none;" title="Chinese art">Chinese</a>,<span>&nbsp;</span><a href="https://en.wikipedia.org/wiki/Indian_art" style="text-decoration: none; color: rgb(6, 69, 173); background: none;" title="Indian art">Indian</a><span>&nbsp;</span>and<span>&nbsp;</span><a href="https://en.wikipedia.org/wiki/Islamic_art" style="text-decoration: none; color: rgb(6, 69, 173); background: none;" title="Islamic art">Islamic</a><span>&nbsp;</span>arts, and also present, due to large population of<span>&nbsp;</span><a href="https://en.wikipedia.org/wiki/Malaysian_Chinese" style="text-decoration: none; color: rgb(6, 69, 173); background: none;" title="Malaysian Chinese">Chinese</a><span>&nbsp;</span>and<span>&nbsp;</span><a href="https://en.wikipedia.org/wiki/Malaysian_Indians" style="text-decoration: none; color: rgb(6, 69, 173); background: none;" title="Malaysian Indians">Indian</a><span>&nbsp;</span>in 
                        today&#39;s<span>&nbsp;</span><a href="https://en.wikipedia.org/wiki/Demographics_of_Malaysia" style="text-decoration: none; color: rgb(6, 69, 173); background: none;" title="Demographics of Malaysia">Malaysian demographics</a>.</p>
                    <p style="margin: 0.5em 0px; color: rgb(32, 33, 34); font-family: sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
                        <asp:Image ID="Image6" runat="server" ImageUrl="https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/The_Naga_Pelangi_sailing_butterfly.JPG/1280px-The_Naga_Pelangi_sailing_butterfly.JPG" Width="20%" />
                    </p>
                    <p style="margin: 0.5em 0px; color: rgb(32, 33, 34); font-family: sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
                        Colonialism also brought other art forms, such as Portuguese dances and music. During this era, influences from<span>&nbsp;</span><a href="https://en.wikipedia.org/wiki/Portuguese_art" style="text-decoration: none; color: rgb(6, 69, 173); background: none;" title="Portuguese art">Portuguese</a>,<span>&nbsp;</span><a href="https://en.wikipedia.org/wiki/Dutch_art" style="text-decoration: none; color: rgb(6, 69, 173); background: none;" title="Dutch art">Dutch</a>, and the<span>&nbsp;</span><a href="https://en.wikipedia.org/wiki/Art_of_the_United_Kingdom" style="text-decoration: none; color: rgb(6, 69, 173); background: none;" title="Art of the United Kingdom">British</a>, were also visible especially in terms of fashion and architecture in many colonial towns of<span>&nbsp;</span><a href="https://en.wikipedia.org/wiki/British_Malaya" style="text-decoration: none; color: rgb(6, 69, 173); background: none;" title="British Malaya">Malaya</a><span>&nbsp;</span>and<span>&nbsp;</span><a href="https://en.wikipedia.org/wiki/Borneo" style="text-decoration: none; color: rgb(6, 69, 173); background: none;" title="Borneo">Borneo</a><span>&nbsp;</span>such 
                        as<span>&nbsp;</span><a href="https://en.wikipedia.org/wiki/Penang" style="text-decoration: none; color: rgb(6, 69, 173); background: none;" title="Penang">Penang</a>,<span>&nbsp;</span><a href="https://en.wikipedia.org/wiki/Malacca" style="text-decoration: none; color: rgb(6, 69, 173); background: none;" title="Malacca">Malacca</a>,<span>&nbsp;</span><a href="https://en.wikipedia.org/wiki/Kuala_Lumpur" style="text-decoration: none; color: rgb(6, 69, 173); background: none;" title="Kuala Lumpur">Kuala Lumpur</a>,<span>&nbsp;</span><a href="https://en.wikipedia.org/wiki/Kuching" style="text-decoration: none; color: rgb(6, 69, 173); background: none;" title="Kuching">Kuching</a><span>&nbsp;</span>and<span>&nbsp;</span><a href="https://en.wikipedia.org/wiki/Kota_Kinabalu" style="text-decoration: none; color: rgb(6, 69, 173); background: none;" title="Kota Kinabalu">Jesselton</a>. Despite the influences of aboard, the indigenous art of Malaysia continues to survive among the<span>&nbsp;</span><a href="https://en.wikipedia.org/wiki/Orang_Asli" style="text-decoration: none; color: rgb(6, 69, 173); background: none;" title="Orang Asli">Orang 
                        Asli</a><span>&nbsp;</span>of peninsular and numerous ethnic groups in Sarawak and Sabah.</p>
                    <p style="margin: 0.5em 0px; color: rgb(32, 33, 34); font-family: sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
                        <asp:Image ID="Image7" runat="server" ImageUrl="https://upload.wikimedia.org/wikipedia/commons/d/db/Malaysiakite.jpg" Width="20%" />
                    </p>
                    <p style="margin: 0.5em 0px; color: rgb(32, 33, 34); font-family: sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
                        Nowadays, given the globally influenced and advanced technology, the younger generation of Malaysian artists have moved from the traditional material such as wood, metals, and forest products, and becoming actively involved in different forms of arts, such as animation, photography, painting, sculpture, and street art. Many of them attaining international recognition for their artworks and exhibitions worldwide, combining styles from all over the world with the traditional Malaysian traditions.</p>
                </asp:View>
            </asp:MultiView>
        </div>
    </div>
</asp:Content>
